### PR TITLE
fix a writer panic

### PR DESCRIPTION
**Pull request by emilien-puget**
fix a writer panic when the close function of the writer is called when no write has been done by initialising the writer with a noop span

### CODE REVIEW

**Comment by emilien-puget** [comment]
to be noted that the CI is broken

**Comment by ndreno** [comment]
Can we have a review of this by any chance fellas?

**Review by dhontecillas — APPROVED** [review]
Good catch. Thank you very much for your contribution, and apologies for not being able to review it sooner.

**Comment by ndreno** [comment]
hey guys, there is the little sister here also https://github.com/krakend/krakend-otel/pull/32

**Pull request merged**
