### PR TITLE
fix a reader panic

### PR DESCRIPTION
**Pull request by emilien-puget**
fix a reader panic when the close function of the reader is called when no reader has been done

### CODE REVIEW

**Comment by ndreno** [comment]
Would you be able to create a tag after reviewing and merging this PR please?

**Review by dhontecillas — APPROVED** [review]
Thanks for your contribution!

**Comment by ndreno** [comment]
thanks guys!

**Comment by dhontecillas** [comment]
A new KrakenD Community Edition version will be released very soon with these fixes, and some other improvements :) 

Thank you

**Pull request merged**
